openapi: 3.0.1
info:
  title: Wisetack API
  version: "1.1.1"
  description: |
    ## Introduction
    With Wisetack customers can pay over time for a purchase, and a business gets paid upfront. The Wisetack APIs enable seamless integration of consumer financing options
    within another system serving businesses and their customers. Here's a brief overview of the APIs:

    * **Transactions** initiates a transaction between a specific business and a customer.
    The Transaction resource also allows tracking and updating the flow of the transaction through authorization and settlement.

    * **PaymentLink** allows a specific type of transaction that starts from an HTML link embedded in an invoice or payment flow. This
    link will initiate a transaction that is session specific for that invoice.

    * **Merchants** allows enabling merchants to offer financing as a payment option, listing existing merchants based on
    date and status filters, getting information on a merchant, and removing merchants from the system.

    * **Users** Each merchant can have multiple users for the Wisetack system. The Users resource allows adding and managing users and their roles and privileges in the system.

    ## Authentication
    Wisetack uses HTTP Basic Authentication with both an application token and a secret key. When you initially create
    a Wisetack account, you'll be given an application token and a secret key for both the production system
    and a test system.  You'll be able to distinguish between the two keys easily by their prefix. Production keys
    start with ws_prod_ and the test system keys are prefixed by ws_test_.
    If you use one of our language SDK's you don't need to worry about the specifics of authentication but if you
    want to build authentication in to your own RESTful calls, you simply add the keys to the header like this:

    1. Concatenate the application token and secret key separated by a colon.

    2. Base64 encode the resulting string.

    3. Pass the result in the authorization header, prefixed with the word Basic.

    This process will result in a header that looks something like this: \
    **Authorization: Basic ZHBERDZ6NG9sT1NJN040Zk1Dc0FsS2pGYTdyZUJZaHU6b0ptM25pUVgxUGR5NRNDU=**

security:
  - BasicAuth: []

tags:
  - name: Transactions
    description: |
      The Transaction resource initiates transactions and manages the flow of authorization, settlement, and refunds.
  - name: PaymentLink
    description: |
      PaymentLink allows a specific type of transaction that starts from an HTML link embedded in an invoice
      or payment flow. This link will initiate a transaction that is session specific for that invoice.
  - name: Merchants
    description: |
      The Merchant resource allows you to onboard merchants, to delete merchants from your system,
      to list all merchants, and to get information on individual merchants.

      There are two different types of data in the MerchantObject.

      * **Flag Fields**
      indicate which fields need to be collected from the merchant. These flag fields are in
      MerchantOptionalInformation and MerchantDataRequired schemas. Their presence indicates that they
      must be collected.

      * **Data Fields** are string fields where the data collected in response to the Flag Fields above
      can be sent back to the server. These fields are in the MerchantUpdateObject.

      Additionally, there are four different flag field sections. Where a flag field is found (if at all)
      indicates how the client should behave regarding that field.

      * **optionalInformation** indicates that this information has not been collected. It is not required
      but could be helpful in future dealings with this merchant.

      * **currentlyDue** are the fields the merchant must supply to transact.

      * **eventuallyDue** are the fields the merchant must supply to have the full range of
      capabilities they are eligible for.

      * **pastDue** are the fields the merchant must supply to continue or restore their transaction
      capabilities.

  - name: Users
    description: |
      The Users resource allows you to support multiple users, each with their own roles and privileges in the
      Wisetack system. This feature allows merchants to add and manage employees and other types
      of subusers.


# Reusable code snippets are all below this line.

x-cors-options: &corsOptions
  options:
    summary: CORS support
    description: Enable CORS by returning correct headers
    tags:
      - CORS
    x-amazon-apigateway-integration:
      type: mock
      requestTemplates:
        application/json: |
          {
            "statusCode" : 200
          }
      responses:
        "default":
          statusCode: "200"
          responseParameters:
            method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-IO-Blackbox'"
            method.response.header.Access-Control-Allow-Methods: "'GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH'"
            method.response.header.Access-Control-Allow-Origin: "'*'"
    responses:
      '200':
        description: Default responnse for CORS method
        headers:
          Access-Control-Allow-Headers:
            content:
              application/json:
                schema:
                  type: "string"
          Access-Control-Allow-Methods:
            content:
              application/json:
                schema:
                  type: "string"
          Access-Control-Allow-Origin:
            content:
              application/json:
                schema:
                  type: "string"

x-api-request-template: &apiRequestTemplate
  application/json: '#set($allParams = $input.params()) {"apiContext":{"apiId":"$context.apiId", "method":"$context.httpMethod", "sourceIp":"$context.identity.sourceIp", "userAgent":"$context.identity.userAgent", "path":"$context.path", "protocol":"$context.protocol", "requestId":"$context.requestId", "stage":"$context.stage"}, #foreach($type in $allParams.keySet()) #set($params = $allParams.get($type)) "$type" : { "parameterMap" : { #foreach($paramName in $params.keySet()) "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext), #end #end}}, #end "body" : $input.json(''$'')}'

x-api-standard-setup: &apiStandardSetup
  passthroughBehavior: when_no_match
  httpMethod: POST
  requestTemplates:
    <<: *apiRequestTemplate
  responses:
    default:
      statusCode: '200'
      responseParameters:
        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-IO-Blackbox'"
        method.response.header.Access-Control-Allow-Methods: "'*'"
        method.response.header.Access-Control-Allow-Origin: "'*'"
  type: aws

x-api-setup-with-standard-errors: &apiSetupStdErrs
  httpMethod: POST
  requestTemplates:
    application/json: '#set($allParams = $input.params()) {"apiContext":{"apiId":"$context.apiId", "method":"$context.httpMethod", "sourceIp":"$context.identity.sourceIp", "userAgent":"$context.identity.userAgent", "path":"$context.path", "protocol":"$context.protocol", "requestId":"$context.requestId", "stage":"$context.stage"}, #foreach($type in $allParams.keySet()) #set($params = $allParams.get($type)) "$type" : { "parameterMap" : { #foreach($paramName in $params.keySet()) "$paramName" : "$util.escapeJavaScript($params.get($paramName))" #if($foreach.hasNext), #end #end}}, #end "body" : $input.json(''$'')}'
  responses:
    default:
      statusCode: '200'
      responseParameters:
        method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-IO-Blackbox'"
        method.response.header.Access-Control-Allow-Methods: "'*'"
        method.response.header.Access-Control-Allow-Origin: "'*'"
    ".*httpStatus\\\":404.*":
      statusCode: '404'
      responseTemplates:
        application/json: "#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))\n#set ($bodyObj = $util.parseJson($input.body))\n{\n  \"type\" : \"$errorMessageObj.errorType\",\n  \"message\" : \"$errorMessageObj.message\",\n  \"request-id\" : \"$errorMessageObj.requestId\"\n}"
    ".*httpStatus\\\":400.*":
      statusCode: '400'
      responseTemplates:
        application/json: "#set ($errorMessageObj = $util.parseJson($input.path('$.errorMessage')))\n#set ($bodyObj = $util.parseJson($input.body))\n{\n  \"type\" : \"$errorMessageObj.errorType\",\n  \"message\" : \"$errorMessageObj.message\",\n  \"request-id\" : \"$errorMessageObj.requestId\"\n}"
  type: aws

x-standard-headers: &stdHeaders
  headers:
    Access-Control-Allow-Headers:
      $ref: '#/components/headers/accessControl'
    Access-Control-Allow-Methods:
      $ref: '#/components/headers/accessControl'
    Access-Control-Allow-Origin:
      $ref: '#/components/headers/accessControl'

x-standard-error-responses: &stdErrResponses
  '404':
    description: Resource not found.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'
  '400':
    description: Bad request.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'
  '403':
    description: Forbidden.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'
  '401':
    description: Unauthorized.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'
  '409':
    description: Conflict.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'
  '500':
    description: Internal server error.
    content:
      application/json:
        schema:
          $ref:  '#/components/schemas/Error'


# End of reusable code snippets

paths:

  /merchant/{merchantId}/transactions:
    summary: Initiates a transaction process.
    description: The Transaction resource initiates a transcation and manages the flow of authorization, settlement, and refunds.
    post:
      summary: POST initiates a transaction process.
      description: |
        When a transaction is initiated, the customer receives a text message with a link to their application. They can follow the link to complete a short, mobile-optimized flow. To start a transaction, the
        merchant must provide the mobile number of the customer, a transaction amount, and the purpose of the transaction.

        The POST can also include an array of line items to describe the services or products provided as
        well as other optional data described in the TransactionObject. These are optional. We recommend including as much information as possible as the data helps create a better user experience, allows better transaction reporting and reconciliation for the business and customer.
        The following values are required for the POST:

        * status must be set to 'initiated'.

        * a United States domestic mobile phone number is required.

        * a transaction amount is required.

        * a transaction purpose is required.

      tags:
        - Transactions
      parameters:
        - name: merchantId
          in: path
          description: Id for the merchant originating the transaction.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionObject'
        <<: *stdErrResponses
    get:
      summary: GET returns a list of transactions for this merchant.
      description: |
        Returns a list of all the transactions for this merchant.
        A filter can be supplied using a query string to limit the list to a date range, status, or number of items.
      tags:
        - Transactions
      parameters:
        - name: merchantId
          in: path
          description: Id for the merchant originating the transaction.
          required: true
          schema:
            type: string
        - name: startingAfter
          in: query
          description: List only transactions that were initiated after this date.
          schema:
            type: string
        - name: endingBefore
          in: query
          description: List only transactions that were initiated before this date.
          schema:
            type: string
        - name: limit
          in: query
          description: Limit the number of transactions returned to this number.
          schema:
            type: string
        - name: status
          in: query
          description: List only transactions with this status code.
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionResourceURL:
                      description: URL pointing to each applicable resource.
        <<: *stdErrResponses

  /transactions/{transactionId}:
    description: Tracks the progress of and allows updating of the transaction.
    parameters:
      - name: transactionId
        in: path
        description: UUID Id for the transaction. Acquired during the POST to create the transaction.
        required: true
        schema:
          type: string
    get:
      summary: GET retrieves information, including the status, on a specific transaction.
      tags:
        - Transactions
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionObject'
    patch:
      summary:  PATCH allows status update for transaction initiation and provides for full or partial refunds.
      tags:
        - Transactions
      description: |
        Supported statuses for transactions:

        * Initiated: The transaction process has been started for a customer but has not yet proceeded through authorization.

        * Authorized: Wisetack has authorized the transactionn for this customer. The transaction is not complete until the status is set to 'settled.' An authorized transaction can either be 'settled' or 'canceled'. An authorized transaction will expire after 30 days if it has not been settled.

        * Settled: Once the transaction is settled, funds are sent to the merchant. A settled transaction can be either partially or completely refunded.

        * Refunded:  The full amount of the transaction has been refunded.

        * Expired: The transaction was not authorized or settled within the specified time limit. A transaction can never be removed from an expired state.

        * Declined: The transaction was declined.

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionObject'

  /merchants:
    description: Resource for merchant onboarding and management.
    post:
      summary: POST creates a merchant and returns a newly created merchant id.
      description: |
        POST creates a new merchant entry. To onboard a merchant, please see the Merchant PATCH operation.

        If there is already a unique merchant entry for this merchant, a 201 error is returned with a link to the resource.
        The state of the application verification process
        is indicated in three main sections: information currently due, due soon, and overdue.
      tags:
        - Merchants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    merchantResourceURL:
                      description: URL pointing to each applicable merchant resource.
                      type: string
        <<: *stdErrResponses
    get:
      summary: GET retrieves a list of merchants.
      description: |
        Lists all merchants on your Wisetack account. You can filter this list based on date and if their transaction initiation has or has not been enabled.
      tags:
        - Merchants
      parameters:
        - name: startingAfter
          in: query
          description: List only merchants who initiated their onboard after this date.
          schema:
            type: string
        - name: endingBefore
          in: query
          description: List only merchants who initiated their onboarding before this date.
          schema:
            type: string
        - name: transactionsEnabled
          in: query
          description: Set to true or false.
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantObject'
        <<: *stdErrResponses

  /merchants/{merchantId}:
    description: Resource for handling merchant onboarding and management.
    parameters:
      - name: merchantId
        in: path
        description: The merchant id as stored during merchant onboarding.
        required: true
        schema:
          type: string
    get:
      summary: GET retrieves merchant information based on merchant id.
      description: |
        Get a merchant's information.
      tags:
        - Merchants
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantObject'
        <<: *stdErrResponses
    patch:
      summary: PATCH onboards a merchant and updates merchant information.
      description: |
        The PATCH (update) is the merchant identification process. The application can request required information from the
        merchant and submit additional information using a PATCH request to the merchantId. Any additional required information
        is returned as a response to the PATCH. This process can continue until all required information is gathered.

        Please see the overview for Merchants for a more detailed explanation for this process.
      tags:
        - Merchants
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MerchantObject'
    delete:
      summary: DELETE removes a merchant from the system.
      description: |
        Remove this merchant from your system.
      tags:
        - Merchants
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  merchantId:
                    description: The id of the merchant deleted.
                    type: string
                  deleted:
                    description: True if successful.
                    type: boolean

  /merchant/{merchantId}/paymentLink:
    summary: Provides a link that can be embedded in an invoice.
    description: |
      PaymentLink allows a specific type of transaction that starts from an HTML link embedded in an invoice
      or payment flow. This link will initiate a transaction session specific for that invoice.
    post:
      summary: POST creates a link to be embedded in an invoice.
      description: |
        You can use the paymentLink resource to create links that can be embedded in invoices or payment flows. PaymentLink allows sending data that will
        make it easier for the customer to complete the transaction. When you send additional information when creating a payment link,
        Wisetack uses it to pre-fill transaction information and make the customer's experience easier.

        Creating a payment link requires a transaction amount and purpose.  Optional fields such as customer address, dob,
        and ssn as well as optional line item information is also supported. The POST returns a link that is specific for
        that customer, merchant, and line items. When the customer clicks the link, they will proceed to a transaction flow specific to that transaction. A unique link will be created on each create. The link expires after 90 days.
      tags:
        - PaymentLink
      parameters:
        - name: merchantId
          in: path
          description: Id for the merchant originating the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentLinkObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentLinkObject'
        <<: *stdErrResponses

  /merchant/{merchantId}/users:
    description: Merchants will have employees (users) who will use the merchant account. Each of these users can offer POS financing.
    parameters:
      - name: merchantId
        in: path
        description: The merchant id as stored during merchant onboarding.
        required: true
        schema:
          type: string
    post:
      summary: POST creates a new user.
      description: |
        POST creates a new user based on the user's phone number. If the mobile phone number is already associated
        with the merchant then the user's already existing id is returned in the response.
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserObject'
        <<: *stdErrResponses
    get:
      summary: GET retrieves a list of users.
      description: |
        List all users for the merchant with {merchantId}.
      tags:
        - Users
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userResourceURL:
                      description: URL pointing to each applicable user resource.
        <<: *stdErrResponses

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        description: The unique UUID representing this user.
        required: true
        schema:
          type: string
    get:
      summary: GET retrieves any available information for the user.
      description: Get any available information for the user.
      tags:
        - Users
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserObject'
    put:
      summary: PUT updates the information for an existing user.
      description: Update the information for an existing user.
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserObject'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserObject'
        <<: *stdErrResponses
    delete:
      summary: DELETE removes a user.
      description: Permanently deletes a user from the system.
      tags:
        - Users
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    description: The id of the user deleted.
                    type: string
                  deleted:
                    description: True if successful.
                    type: boolean
        <<: *stdErrResponses

  /subscribe:
    post:
      summary: POST subscribes to all Wisetack callbacks.
      description: |
        Wisetack provides callbacks to let you know when the status of a transaction has changed. Each time
        the status of a loan application changes, Wisetack will send a request to this URL. The request contains
        the new status, the loan application id, and a secret key provided to you by Wisetack. You should only accept
        incoming status changes after verifying the secret key. When your webhook is called, it will receive
        a StatusUpdateRequest. Please see the StatusUpdateRequest in the Schema section below.

        Statuses:

        * **Initiated:**  You sent a transaction to your customer but they have not submitted an application.

        * **Authorized:**  We approved the application but the customer has not accepted the loan documents.

        * **Declined:** We were unable to approved the application.

        * **Confirmed:** The customer has accepted the loan documents and confirmed the purchase.

        * **Settled:** We've sent the funds to your bank account.

        * **Refunded:** The customer requested and received a refund.

      tags:
        - Webhooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscribeObject'
      responses:
        '201':
          description: Webhook created.
        <<: *stdErrResponses


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic


  headers:
    accessControl:
      content:
        application/json:
          schema:
            type: "string"

  schemas:

    MerchantObject:
      properties:
        merchantId:
          description: A UUID unique to the newly created merchant.
          type: string
        onboardingDate:
          description: Date this merchant was initially onboarded in YYYY-MM-DD format.
          type: string
        transactionsEnabled:
          description: Has this merchant been fully onboarded and are now able to initiate transactions.
          type: boolean
        merchantSecretToken:
          description: An token used for authenticiation from the partner's backend to the Wisetack backend.
        optionalInformation:
          $ref: '#/components/schemas/MerchantOptionalInformation'
        currentlyDue:
          $ref: '#/components/schemas/MerchantDataRequired'
        eventuallyDue:
          $ref: '#/components/schemas/MerchantDataRequired'
        pastDue:
          $ref: '#/components/schemas/MerchantDataRequired'
        disabledReason:
          description: If the merchant has been disabled and cannot initiate further transactions, that information is listed here.
          type: string
        merchantInformation:
          $ref: '#/components/schemas/MerchantUpdateObject'

    MerchantOptionalInformation:
      properties:
        companyDescription:
          description: Freeform description of the business.
        companyURL:
          description: The main url for the business.
        dba:
          description: Any doing-business-as names that would apply.
        companyEmail:
          description: Email address for main contact at the company.
        annualRevenue:
          description: Total annual revenue for the business. Includes two decimal points but no dollar symbol.
        averageOrderValue:
          description: The typical order value for this business. Includes two decimal points but no dollar symbol.
        industry:
          description: A list of industries will be provided and this field will be validated.
        dateEstablished:
          description: The date the company was started in YYYY-MM-DD format.
        supportPhone:
          description: Business phone number for customer support.
        annualChargeBackAmount:
          description: Total amount of chargebacks for the prior year.
        annualRefundsAmount:
          description: Total amount of refunds for the prior year.
        otherServiceLinks:
          description: |
            Future feature. This section will request access to external services, such as Quicken, to facilitate onboarding.
          type: array
          items:
            type: object
            properties:
              serviceName:
                description: The name of the company providing the service. Quicken, for example.
                type: string
        ownerInformation:
          description: Optional information for each owner.
          type: array
          items:
            type: object
            properties:
              driversLicenseNumber:
                description: Driver's license number.
              driversLicenseState:
                description: State where driver's license was issued.
              ownerDocuments:
                description: Scanned in documents to supplement and verify information.
                type: array
                items:
                  type: object
                  properties:
                    documentType:
                      description: Enum describing type of document requested or required.

    MerchantDataRequired:
      properties:
        deadline:
          type: string
          description: The date information is the section is due in YYYY-MM-DD format.
        companyEIN:
          description: The company's Employer Identification Number.
        companyLegalOperatingName:
          description: The official name of the company as listed with the tax authority.
        companyPhoneNumber:
          description: Main contact number for the company.
        companyStreetAddress1:
          description: Address of the business.
        companyStreetAddress2:
          description: Address of the business.
        companyCity:
          description: City of the business.
        companyStateCode:
          description: Two-character code for the state in which the business is based.
        companyZip:
          description: Zip code for business location. Zip code can be either the full nine digits (nnnnn-mmmm) or just the five digit delivery area.
        companyType:
          description: A list of business types will be provided and this field will be validated.
          enum:
            - partnership
            - LLC
            - corporation
        tosAcceptanceDate:
          description: Date the terms of service were accepted. Format is YYYY-MM-DD.
        tosAcceptanceIPAddress:
          description: IP address used when terms of service were accepted.

        ownerInformation:
          description: Required information for each owner.
          type: array
          items:
            type: object
            properties:
              isOwnerPrimary:
                description: Indicates whether this owner is the primary business owner.
              ownerMobilePhoneNumber:
                description: Cell phone number of the company owner.
              ownerDOB:
                description: Date-of-birth of the company owner. Format is YYYY-MM-DD.
              ownerFirstName:
                description: First name of the owner.
              ownerLastName:
                description: Last name of the owner.
              ownerLast4ssn:
                description: Social security number of the owner.

    MerchantUpdateObject:
      properties:
        companyEIN:
          description: The company's Employer Identification Number.
          type: string
        companyLegalOperatingName:
          description: The official name of the company as listed with the tax authority.
          type: string
        companyPhoneNumber:
          description: Main contact number for the company.
          type: string
        companyStreetAddress1:
          description: Address of the business.
          type: string
        companyStreetAddress2:
          description: Address of the business.
          type: string
        companyCity:
          description: City of the business.
          type: string
        companyStateCode:
          description: Two-character code for the state in which the business is based.
          type: string
        companyZip:
          description: Zip code for business location. Zip code can be either the full nine digits (nnnnn-mmmm) or just the five digit delivery area.
          type: string
        companyType:
          description: A list of business types will be provided and this field will be validated.
          enum:
            - partnership
            - LLC
            - corporation
        tosAcceptanceDate:
          description: Date terms of service were accepted. Format is YYYY-MM-DD.
          type: string
        tosAcceptanceIPAddress:
          description: IP address used when terms of service were accepted.
          type: string
        commpanyDescription:
          description: Freeform description of the business.
          type: string
        companyURL:
          description: The main url for the business.
          type: string
        dba:
          description: Any doing-business-as names that would apply.
          type: string
        companyEmail:
          description: Email address for main contact at the company.
          type: string
        annualRevenue:
          description: Total annual revenue for the business. Includes two decimal points but no dollar symbol.
          type: string
        averageOrderValue:
          description: The typical order value for this business. Includes two decimal points but no dollar symbol.
          type: string
        industry:
          description: A list of industries will be provided and this field will be validated.
          type: string
        dateEstablished:
          description: The date the company was started in YYYY-MM-DD format.
          type: string
        supportPhone:
          description: Business phone number for customer support.
          type: string
        annualChargeBackAmount:
          description: Total amount of chargebacks for the prior year.
          type: string
        annualRefundsAmount:
          description: Total amount of refunds for the prior year.
          type: string
        otherServiceLinks:
          description: |
            Future feature. This section will allow other services, such as Quicken, to facilitate onboarding.
          type: array
          items:
            type: object
            properties:
              serviceName:
                description: The name of the company providing the service. Quicken, for example.
              serviceURL:
                description: The url for the support page for the service.
              serviceToken:
                description: Customer token needed to access the service.
        ownerInformation:
          description: Optional information for each owner.
          type: array
          items:
            type: object
            properties:
              ownerMobilePhoneNumber:
                description: The cell phone number of the merchant.
                type: string
              driversLicenseNumber:
                description: Driver's license number.
                type: string
              driversLicenseState:
                description: State where driver's license was issued.
                type: string
              ownerDocuments:
                description: Scanned in documents to supplement and verify information.
                type: array
                items:
                  type: object
                  properties:
                    documentType:
                      description: Enum describing type of document requested or required.
                      type: string

    PaymentLinkObject:
      properties:
        paymentLink:
          type: string
          description: This link is created and can be embedded in invoices. When the customer clicks this link,
            they will proceed to a web page that will initiate a transaction for that customer.
        transactionAmount:
          type: string
          description: Required for POST. Includes two decimal points but no dollar symbol.
        mobileNumber:
          type: string
          description: Optional. International phone numbers are supported. No formatted should be included. Just the digits.
        transactionPurpose:
          type: string
          description: Required for POST. Currently this is freeform but will be enumerated in database in the future.
        firstName:
          type: string
          description: Optional
        lastName:
          type: string
          description: Optional
        email:
          type: string
          description: Optional
        dob:
          type: string
          description: Optional. Format is YYYY-MM-DD. Please use the whole format as shown below in the example.
        ssn4:
          type: string
          description: Optional.
        ssn:
          type: string
          description: optional
        streetAddress1:
          type: string
          description: optional
        streetAddress2:
          type: string
          description: optional
        city:
          type: string
          description: optional
        stateCode:
          type: string
          description: optional
        zip:
          type: string
          description: Optional. Zip code can be either the full nine digits (nnnnn-mmmm) or just the five digit delivery area.
        employer:
          type: string
          description: optional
        annualIncomeBeforeTaxes:
          type: string
          description: Optional. Includes the decimal point but no dollar sign.
        coborrowerMobileNumber:
          type: string
          description: Optional. Coborrower mobile number. International phone numbers are supported. No formatted should be included. Just the digits.
        transactionLineItems:
          type: array
          items:
            $ref: '#/components/schemas/PaymentLinkLineItems'
      example:
        paymentLink: http://business.wisetack.us/loanApplicationId=80349125-3b0c-4fd6-b2ef-568a4844321d
        transactionAmount: '1000.00'
        mobileNumber: 1235554567
        transactionPurpose: landscape
        firstName: Clark
        lastName: Smith
        email: casmith@example.com
        dob: 1953-01-13
        ssn4: 3333
        streetAddress: 123 Ashton Street
        streetAddress2: Suite 13
        city: Auburn
        state: CA
        zip: 95602
        annualIncomeBeforeTaxes: '950000.00'
        coborrowerMobileNumber: 5555556767


    PaymentLinkLineItems:
      properties:
        productDescription:
          type: string
        SKU:
          type: string
        pricePerUnit:
          type: string
          description: Includes the decimal point but no dollar sign.
        tax:
          type: string
          description: Includes the decimal point but no dollar sign.
        discount:
          type: string
          description: Includes the decimal point but no dollar sign.
        totalAmount:
          type: string
          description: Includes the decimal point but no dollar sign.
        photo:
          type: string
          description: To be fixed to use media attachment later.
      example:
        productDescription: labor
        SKU: none
        pricePerUnit: '50000.00'
        tax: na
        discount: '5000.00'
        totalAmount: '55000.00'

    TransactionObject:
      properties:
        status:
          description: 'Indicates the current state of the transaction: initiated, authorized, settled, refunded, expired, or decined.'
          type: string
          enum: [initiated, authorized, confirmed, settled, refunded, expired, declined]
        transactionAmount:
          type: string
          description: Required for POST. Includes two decimal points but no dollar symbol.
        mobileNumber:
          type: string
          description: Required for POST. International phone numbers are supported. No formatted should be included. Just the digits.
        transactionPurpose:
          type: string
          description: Required for POST. Currently this is freeform but will be enumerated in database in the future.
        firstName:
          type: string
          description: optional
        lastName:
          type: string
          description: optional
        email:
          type: string
          description: optional
        dob:
          type: string
          description: Optional. Format is YYYY-MM-DD. Please use the whole format as shown below in the example.
        ssn4:
          type: string
          description: Optional.
        ssn:
          type: string
          description: optional
        streetAddress1:
          type: string
          description: optional
        streetAddress2:
          type: string
          description: optional
        city:
          type: string
          description: optional
        stateCode:
          type: string
          description: optional
        zip:
          type: string
          description: Optional. Zip code can be either the full nine digits (nnnnn-mmmm) or just the five digit delivery area.
        employer:
          type: string
          description: optional
        annualIncomeBeforeTaxes:
          type: string
          description: Optional. Includes the decimal point but no dollar sign.
        coborrowerMobileNumber:
          type: string
          description: Optional. Coborrower mobile number. International phone numbers are supported. No formatted should be included. Just the digits.
        transactionLineItems:
          type: array
          items:
            $ref: '#/components/schemas/TransactionLineItems'
      example:
        status: initiated
        transactionAmount: '1000.00'
        mobileNumber: 1235554567
        transactionPurpose: landscape
        firstName: Clark
        lastName: Smith
        email: casmith@example.com
        dob: 1953-01-13
        ssn4: 3333
        streetAddress: 123 Ashton Street
        streetAddress2: Suite 13
        city: Auburn
        state: CA
        zip: 95602
        annualIncomeBeforeTaxes: '950000.00'
        coborrowerMobileNumber: 5555556767


    TransactionLineItems:
      properties:
        productDescription:
          type: string
        SKU:
          type: string
        pricePerUnit:
          type: string
          description: Includes the decimal point but no dollar sign.
        tax:
          type: string
          description: Includes the decimal point but no dollar sign.
        discount:
          type: string
          description: Includes the decimal point but no dollar sign.
        totalAmount:
          type: string
          description: Includes the decimal point but no dollar sign.
        photo:
          type: string
          description: To be fixed to use media attachment later.
      example:
        productDescription: labor
        SKU: none
        pricePerUnit: '50000.00'
        tax: na
        discount: '5000.00'
        totalAmount: '55000.00'

    UserObject:
      properties:
        userId:
          description: UUID uniquely identifying the user.
          type: string
        firstName:
          description: The first name of the user.
          type: string
        lastName:
          description: The last name of the user.
          type: string
        email:
          description: Email address of the user.
          type: string
        mobilePhone:
          description: The user's cell phone number.
          type: string
        userName:
          description: A log in name for the user.
          type: string
        password:
          description: SHA-256 encrypted string representing the password.
          type: string
        role:
          description: Role for user.
          type: string
          enum:
            - admin
            - employee
            - reviewer
        group:
          description: Users can be assigned to a group and will inherit the rights and privileges assigned to that group.
          type: string
      example:
        userId: 6f6c4bf4-ab58-4a1b-833e-0e665dc65400
        firstName: Hugh
        lastName: Cave
        email: hugh@akhouse.com
        mobilePhone: 5556669999
        userName: hughb
        password: sample
        role: admin
        group: na

    SubscribeObject:
      properties:
        callbackURL:
          description: The URL on your system for Wisetack to call when the request event triggers.
          type: string
          required: true
          format: uri
          example: https://wisetack.yourcompany.com/callback
        event:
           description: The event you want to subscribe to. Presently only 'transaction-status' is available.
           type: string
           required: true
           example: transaction-status
        secretKey:
           type: string
           required: true
           description: This value will be sent to you each time Wisetack calls your endpoint. You must
              must verify this value is in the request for security purposes.
           example: c58459b9-5acc-4d8b-b6a5-4e3cd39fff9c

    StatusUpdateRequest:
      properties:
        transactionId:
          description: UUID uniquely identifying the transaction with changed status.
          type: string
        changedStatus:
          description: The new status of this loan application.
          type: string
          enum:
            - initiated
            - authorized
            - confirmed
            - settled
            - refunded
            - declined
            - expired
        date:
          description: Date that status changed.
          type: string
        loanAmountRequested:
          description: The original loan amount requested by the customer.
          type: string
        approvedLoanAmount:
          description: The loan amount approved for this user by Wisetack. Might be lower than originalLoanAmount
            in the event of a counter offer.
          type: string
        consumer:
          type: object
          properties:
            fullName:
              description: Customer's first and last name.
              type: string
            email:
              description: Customer's email.
              type: string
            phone:
              description: Customer's phone.
              type: string
            zip:
              description: Customer's postal code.
              type: string
        loanPurpose:
          description: Purpose of the loan as entered by merchant.
          type: string
        serviceCompletedOn:
          description: The date by which the service should be completed.
          type: string
        tilaAcceptedOn:
          description: The data the Truth In Lending document was accepted.
          type: string
        createdAt:
          description: The date the transaction was initiated.
          type: string


    Error:
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        request-id:
          type: string